// Daftar provinsi resmi panel PIHPS Bank Indonesia (id sesuai endpoint
// GetProvinceAll). 0 = rata-rata nasional (tampilan bawaan Radar Harga).
export const PROVINCES = [
  { id: 0, name: 'Nasional (rata-rata)' },
  { id: 1, name: 'Aceh' },
  { id: 2, name: 'Sumatera Utara' },
  { id: 3, name: 'Sumatera Barat' },
  { id: 4, name: 'Riau' },
  { id: 5, name: 'Kepulauan Riau' },
  { id: 6, name: 'Jambi' },
  { id: 7, name: 'Bengkulu' },
  { id: 8, name: 'Sumatera Selatan' },
  { id: 9, name: 'Kepulauan Bangka Belitung' },
  { id: 10, name: 'Lampung' },
  { id: 11, name: 'Banten' },
  { id: 12, name: 'Jawa Barat' },
  { id: 13, name: 'DKI Jakarta' },
  { id: 14, name: 'Jawa Tengah' },
  { id: 15, name: 'DI Yogyakarta' },
  { id: 16, name: 'Jawa Timur' },
  { id: 17, name: 'Bali' },
  { id: 18, name: 'Nusa Tenggara Barat' },
  { id: 19, name: 'Nusa Tenggara Timur' },
  { id: 20, name: 'Kalimantan Barat' },
  { id: 21, name: 'Kalimantan Selatan' },
  { id: 22, name: 'Kalimantan Tengah' },
  { id: 23, name: 'Kalimantan Timur' },
  { id: 24, name: 'Kalimantan Utara' },
  { id: 25, name: 'Gorontalo' },
  { id: 26, name: 'Sulawesi Selatan' },
  { id: 27, name: 'Sulawesi Tenggara' },
  { id: 28, name: 'Sulawesi Tengah' },
  { id: 29, name: 'Sulawesi Utara' },
  { id: 30, name: 'Sulawesi Barat' },
  { id: 31, name: 'Maluku' },
  { id: 32, name: 'Maluku Utara' },
  { id: 33, name: 'Papua' },
  { id: 34, name: 'Papua Barat' },
]

export const PROVINCE_NAME = Object.fromEntries(PROVINCES.map((p) => [p.id, p.name]))
